services:
  python-api:
    build: .  # Assuming Dockerfile and main.py are in the current directory
    container_name: python-api
    volumes:
      - .:/app
    environment:
      - OLLAMA_URL=http://ollama:11434
    networks:
      - ai-network
    depends_on:
      - ollama
      
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    networks:
      - ai-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  
  n8n:
    build:
      context: ./n8n
      dockerfile: Dockerfile
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${NGROK_DOMAIN}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://${NGROK_DOMAIN}/ # Essential for Telegram
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/workflows
    restart: always
    networks:
      - ai-network
    entrypoint: ["/bin/sh", "-c"]
    command: ["n8n import:workflow --separate --input=/home/node/workflows/ && n8n start"]

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    networks:
      - ai-network
    environment:
      - NGROK_AUTHTOKEN=2vU3NJQ9zAjDdth0Zpxg8WJ048A_65qmkaXdjCjaHkPbTm3tJ
    command:
      - "http"
      - "n8n:5678"
      - "--url=${NGROK_DOMAIN}" # Optional: Only if you have a static domain

networks:
  ai-network:
    driver: bridge

volumes:
  ollama_data:
  n8n_data: