services:
  python-api:
    build: .  # Assuming Dockerfile and main.py are in the current directory
    container_name: python-api
    volumes:
      - .:/app
    environment:
      - OLLAMA_URL=http://ollama:11434
    networks:
      - ai-network
    depends_on:
      - ollama
      
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped
    networks:
      - ai-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu

  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    depends_on:
      - ollama
    ports:
      - "3000:8080"
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'HF_TOKEN=' # Add your token here
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
    networks:
      - ai-network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=${NGROK_DOMAIN}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - WEBHOOK_URL=https://${NGROK_DOMAIN}/ # Essential for Telegram
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always
    networks:
      - ai-network

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    networks:
      - ai-network
    environment:
      - NGROK_AUTHTOKEN=2vU3NJQ9zAjDdth0Zpxg8WJ048A_65qmkaXdjCjaHkPbTm3tJ
    command:
      - "http"
      - "n8n:5678"
      - "--url=${NGROK_DOMAIN}" # Optional: Only if you have a static domain

networks:
  ai-network:
    driver: bridge

volumes:
  ollama_data:
  open-webui:
  n8n_data: